name: Build Java Project

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory'
        required: false
        type: string
        default: '.'

      java-version:
        description: 'Java version to use'
        required: true
        type: string

      distribution:
        description: 'Java distribution'
        required: false
        type: string
        default: temurin

      cache:
        description: 'Build cache (maven or gradle)'
        required: false
        type: string
        default: maven

      push-image:
        description: 'Publish Docker image'
        required: false
        type: boolean
        default: false

      docker-image-name:
        description: 'Docker image name (ex: usuario/app)'
        required: false
        type: string

    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          cache: ${{ inputs.cache }}

      - name: Execute Tests
        working-directory: ${{ inputs.working-directory }}
        run: mvn test

      - name: Build Project
        working-directory: ${{ inputs.working-directory }}
        run: mvn clean package -DskipTests=false

      - name: Semantic Versioning by Branch
        if: inputs.push-image
        id: semver
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          pre_release_branches: develop
          pre_release_suffix: dev
          default_bump: patch
      
      - name: Normalize branch name
        if: inputs.push-image
        id: branch
        run: |
          echo "value=${GITHUB_REF_NAME//\//-}" >> $GITHUB_OUTPUT

      - name: Validate Docker secrets and image name
        if: inputs.push-image
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "❌ DOCKERHUB_USERNAME ou DOCKERHUB_TOKEN não configurados."
            echo "⚠️ Configure os secrets no repositório que usa este workflow."
            exit 1
          fi
          if [ -z "${{ inputs.docker-image-name }}" ]; then
            echo "❌ docker-image-name é obrigatório quando push-image é true."
            echo "⚠️ Passe o parâmetro docker-image-name ao executar este workflow."
            exit 1
          fi

      - name: Update Kubernetes manifest with new image tag
        if: github.ref_name == 'main' && inputs.push-image
        run: |
          yq -i '
            .spec.template.spec.containers[0].image =
            "${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.docker-image-name }}:${{ steps.semver.outputs.new_tag }}"
          ' k8s/backend/deployment.yaml

      - name: Commit Kubernetes manifest update
        if: github.ref_name == 'main' && inputs.push-image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add k8s/backend/deployment.yaml

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: update k8s image tag to ${{ steps.semver.outputs.new_tag }}"
          git push
      
      - name: Update pom.xml version with SemVer
        if: github.ref_name == 'main' && inputs.push-image
        working-directory: infocep
        run: |
          mvn versions:set \
            -DnewVersion=${{ steps.semver.outputs.new_tag }} \
            -DgenerateBackupPoms=false

      - name: Commit pom.xml version update
        if: github.ref_name == 'main' && inputs.push-image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add infocep/pom.xml

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: bump version to ${{ steps.semver.outputs.new_tag }}"
          git push

      - name: Docker Login
        if: inputs.push-image
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: inputs.push-image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.working-directory }}
          push: true
          tags: |
             ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.docker-image-name }}:${{ steps.semver.outputs.new_tag }}
             ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.docker-image-name }}:${{ steps.branch.outputs.value }}
